### ISSUE TITLE
Spark Python API Support

### ISSUE THREAD

**Issue by mandoz** [Stratio/spark-rabbitmq#22]
Hello,

I was wondering if its on the roadmap to integrate the Python API as well, or will you only continue supporting Scala and Java?

Best Regards,
Mohannad

**Comment by danielcsant** [comment]
Hi, 

Currently we don't have that necessity but we are open to accept the integration with Python in case you want to contribute to the project.

Regards

**Comment by jocerfranquiz** [comment]
Hi Daniel,

Maybe a middle point into this topic could be to add a helper class like this one:

```
private class PythonHelper {
    def createStream(
        broker: String,
        queue: String,
        jssc: JavaStreamingContext,
        storageLevel: StorageLevel): JavaReceiverInputDStream[JMSEvent] = {
            RabbitMQUtils.createStream(jssc, brokerURL, queuename, storageLevel)
        }
}
```
into the file [RabbitMQUtils.scala](https://github.com/Stratio/Spark-RabbitMQ/blob/master/src/main/scala/org/apache/spark/streaming/rabbitmq/RabbitMQUtils.scala).

I try to do it myself, but I don't know how to get rid of the `messageHandler`. If we have this helper, we can use a .jar from Stratio and call it like this in Python:

`my_helper_class = (ssc._jvm.java.lang.Thread.currentThread()
.getContextClassLoader()
.loadClass("org.apache.spark.streaming.rabbitmq.PythonHelper"))`

**Comment by lookfwd** [comment]
Using `RabbitMQUtils.createJavaStream()` didn't work for me. It wasn't streaming anything for some funny reason.

What I ended up doing and worked is to use more or less the code in this [patch](https://github.com/lookfwd/spark/commit/26b22a62112137d8052ae90e8190ed05456b28ac) (code adapted mostly from the kinesis driver). Then one rebuilds spark and gets a new `spark/external/rabbitmq/target/spark-streaming-rabbitmq_2.10-1.6.1.jar`. I'm sure that this code can live outside spark as well but that's how I did it for now.

Little changes on that patch were to change the return type from: `InputDStream[String]` to `JavaInputDStream[String]`, remove the `withNamedScope` and convert `RabbitMQUtils.createDistributedStream` line to `JavaInputDStream.fromInputDStream(RabbitMQUtils.createDistributedStream[String](...))`.

On the Python part pretty much copied [this](https://github.com/apache/spark/blob/v1.6.1/python/pyspark/streaming/kinesis.py) and can be built with `build/mvn -DskipTests package -pl assembly`.

I have to use the full `mvn clean install` instead of just `mvn clean package -pl com.stratio.receiver:spark-rabbitmq_1.6`.

Then I can run by doing:

```
bin/spark-submit --jars 
    /<absolute path to>/com/stratio/receiver/spark-rabbitmq_1.6/0.4.0-SNAPSHOT/spark-rabbitmq_
1.6-0.4.0-SNAPSHOT.jar
    ,/<absolute path to>/com/rabbitmq/amqp-client/3.6.1/amqp-client-3.6.1.jar
    ,/<absolute path to>/s
park/external/rabbitmq/target/spark-streaming-rabbitmq_2.10-1.6.1.jar
    my_streaming_program.py
```

This is roughly how it works but I think it's a long way till it's PR-able.

**Comment by compae** [comment]
Hi @lookfwd, 

in the last two PR you can find examples to use the java implementation and I solve the erros with the java objects and the JavaInputDstream. 

In the next PR I add the python implementation, if you want you can send one PR and colaborate with the project.

[Receiver approach in java](https://github.com/Stratio/Spark-RabbitMQ/blob/master/src/test/java/org/apache/spark/streaming/rabbitmq/JavaRabbitMQConsumer.java)

[Distributed approach in java](https://github.com/Stratio/Spark-RabbitMQ/blob/master/src/test/java/org/apache/spark/streaming/rabbitmq/JavaRabbitMQDistributedConsumer.java)

**Comment by lookfwd** [comment]
@compae - that's fantastic! Sure I would like to contribute. If you're about to do a Python implementation, maybe you could do one part and me the other, or me to write any tests or I could make a PR with my  draft from my local repo... although I'm not sure it's worth tons.

**Comment by compae** [comment]
@lookfwd if you want I generate one branch. Then you can make one PR to this branch, after this I review the code and if is necessary, I make more PRs and merge in master the Python implementation.

Are you ok?

**Comment by jocerfranquiz** [comment]
This is awesome!! Thanks @compae and @lookfwd!

I'm just learning scala, but if I can collaborate with you guys please let me know. Is better to have an official implementation and examples :+1:

**Comment by PhilippGrulich** [comment]
Hey @compae and @lookfwd,
thanks for working on this!!

**Comment by tpickett** [comment]
close to merge on the branch?

**Comment by mirelagrigoras** [comment]
Hello, @compae and @lookfwd ! Has the python implementation been added to the master yet?
